### ISSUE TITLE
Using restify-enroute + mongoose makes me loose the connection.

### ISSUE THREAD

**Issue by bruno-brant** [restify/enroute#1]
Hi! I'm trying to use restify-enroute on a project that uses mongoose. I'm initializing the connection before even creating the server. When a request is handled, the mongoose instance is not connected. 

I've created a [repo with an example](https://github.com/HeavyStorm/mongoose-enroute-conflict). Right now, I don't know who's to blame - probably just my lack of expertise concerning NodeJS and Restify - but if someone could help, it'd be appreciated.

**Comment by micahr** [comment]
@leitsubomi do you mind helping @HeavyStorm out?

**Comment by bruno-brant** [comment]
A small update: I've debugged your code step by step, adding checks for `mongoose.connection.readyState` in every place I could think of. 

My perception is that require cache isn't working at some point, and instead of returning me the same instance from `require("mongoose")`, it's actually returning one new. Your code seems free of anything that could cause it, so right now I'm starting to suspect Node itself (which is crazy, I know).

I'll update this with any findings I have.

**Comment by bruno-brant** [comment]
I finally figured it out. It has nothing to do with enroute.

[This issue](https://github.com/nodejs/node/issues/6978) is the culprit; Two different requires to mongoose are returning the different instances because of a casing issue. 

Thanks for any help.

**Comment by DonutEspresso** [comment]
Glad you figured out! Sorry we didn't get a chance to help you look into it.

**Comment by bruno-brant** [comment]
Hey, no problem! I'm just glad I found it.

**Comment by bruno-brant** [comment]
Guys, I'm reopening the issue because, after studying the behavior of the issue I mentioned, I realized that the workaround has to be done in enroute.

In short, the issue is:
- Some well know modules (such as mongoose) rely on the fact that requiring it many times will yield the same _instance_.
- There is a issue with drive letter casing in Windows in NodeJS, where it will resolve different casings in different situations. This leads to a require cache miss, which leads to different instances of a certain module.
  - Detail: when node `require`s a module, casing seems to follow the callee's full path casing. However, when using `path.resolve`, the drive letter casing is always lower. 

Having said that, enroute uses `path.resolve` (current line 140 of index.js) when no scriptRoot is provided. This leads to a driver letter with lower casing and, in situations where the main script is loaded from a shell that is informing a upper letter, causes caches miss.

**I'm reopening the issue and making a PR to solve the problem.** The PR just checks if the current platform is Win32 and fix the casing (at least when both files are on the same drive letter -- if not, the fix does nothing).

**Comment by yunong** [comment]
Closing as #2 fixes this.
